name: "DiscordBotManager"
version: '1.0'
main: 'net.vitacraft.discordbotmanager_bukkit.DiscordBotManager'
api-version: '1.20'
authors: [Sieadev, Relism]
commands:
  dbm:
    description: Discord Bot Manager
    usage: /dbm <action> <sandboxName>