name: "discordbotmanager"
version: '1.0'
main: 'net.vitacraft.discordbotmanager.DiscordBotManager'
api-version: '1.20'

commands:
  runcmd:
    description: Sends a command to a specific sandbox.
    usage: /runcmd <sandboxName> <commandToSend>