#################################################################
# +-----------------------------------------------------------+ #
# |                    Discord Bot Manager                    | #
# |            Made with <3 by sieadev and Relism             | #
# +-----------------------------------------------------------+ #
#################################################################

debug: true