name: DiscordBotManager
version: '${version}'
main: net.vitacraft.discordbotmanager_paper.DiscordBotManager
api-version: '1.20'
authors: [Sieadev, Relism]
commands:
  dbm:
    description: Discord Bot Manager
    usage: /dbm <action> <sandboxName>
