name: "JarLoader"
version: '1.0'
main: 'net.vitacraft.discordbotmanager_paper.DiscordBotManager'
api-version: '1.20'
authors: [Sieadev, Relism]
commands:
  jl:
    description: JM Jar Loader
    usage: /jl <action> <sandboxName>